### ISSUE TITLE
stuck on loading 

### ISSUE THREAD

**Issue by ruboko** [sheyabernstein/MMM-shabbat#1]
i tried to install that module, it is not telling me that their is any error however the module is stuck on loading while my other modules load. can anyone help me fix this pls

**Comment by sheyabernstein** [comment]
@ruboko Hi, try opening the mirror in your browser. Are you getting any errors in the console?

**Comment by evornov** [comment]
I was having this problem too, with the following error message in the console:
`Failed to load http://www.hebcal.com/shabbat/?cfg=json&b=18&m=50&a=on&geo=pos&...: Redirect from 'http://www.hebcal.com/shabbat/?cfg=json&b=18&m=50&a=on&geo=pos&...' to 'https://www.hebcal.com/shabbat/?cfg=json&b=18&m=50&a=on&geo=pos&...' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://192.168.1.142:8080' is therefore not allowed access.`

Switching the hebcal request URL from http to https resolved it.
