### ISSUE TITLE
hi, module is stuck on "loading"

### ISSUE THREAD

**Issue by avi9899** [sheyabernstein/MMM-shabbat#2]
hi,
i'm trying to make it work but without success.
this in the config:

	},
{
    module: 'MMM-shabbat',
    position: 'middle_center',
    title: 'Zmanim',
    config: {
minutesBefore: "18",
minutesAfter: "50",
ashkenaz: "false",
tzid: "IL",
latitude: "32.018876",
longitude: "34.765101",
updateInterval: "60",
retryDelay: "2500"
           // See 'Configuration options' for more information.
       }
}

**Comment by sheyabernstein** [comment]
Can you check your browser devtools to see the error is?

**Comment by avi9899** [comment]
i'm sorry, there is a guide that explained how to do it?

**Comment by avi9899** [comment]
Refused to apply style from 'http://localhost:8080/css/custom.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
loader.js:203 Error on loading stylesheet: css/custom.css
stylesheet.onerror @ loader.js:203
weatherforecast.js:279 GET https://api.openweathermap.org/data/2.5/forecast/daily?id=294751&units=metric&lang=he&APPID=f5ad9a3b43ff8ef8d9b550114463840f 401 (Unauthorized)
updateWeather @ weatherforecast.js:279
(anonymous) @ weatherforecast.js:400
(index):1 Refused to apply style from 'http://localhost:8080/css/custom.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

**Comment by sheyabernstein** [comment]
Is the mirror working without the plugin?

**Comment by avi9899** [comment]
Which plugin?

בתאריך יום ד׳, 22 בינו׳ 2020 ב-22:02 מאת Sheya Bernstein <
notifications@github.com>:

**Comment by sheyabernstein** [comment]
The MMM-shabbat plugin. It looks like you have an issue with your
custom.css file

**Comment by avi9899** [comment]
I don't think that i have this file at all.
if it need to be in the css folder its not... there is only main.css

‫בתאריך יום ד׳, 22 בינו׳ 2020 ב-22:14 מאת ‪Sheya Bernstein‬‏ <‪
notifications@github.com‬‏>:‬

> The MMM-shabbat plugin. It looks like you have an issue with your
> custom.css file
>

**Comment by sheyabernstein** [comment]
Seems like your mm is missing files
