### ISSUE TITLE
json error

### ISSUE THREAD

**Issue by zachpef** [sheyabernstein/MMM-shabbat#3]
I cloned the module to my modules folder. then I tried to cd to it and do npm install and it gives me this strange error

npm ERR! code EJSONPARSE
npm ERR! file C:\Users\zpfla\Downloads\MagicMirror\modules\MMM-shabbat\package.json
npm ERR! JSON.parse Failed to parse json
npm ERR! JSON.parse Unexpected token ] in JSON at position 302 while parsing near '...,
npm ERR! JSON.parse     "Jewish",
npm ERR! JSON.parse   ],
npm ERR! JSON.parse   "author": "she...'
npm ERR! JSON.parse Failed to parse package.json data.
npm ERR! JSON.parse package.json must be actual JSON, not just JavaScript.

It appears that the json file is just Javascript and not JSON.

**Comment by sheyabernstein** [comment]
Hiya, this has been fixed in f7ae4ca
