### ISSUE TITLE
can't install

### ISSUE THREAD

**Issue by varek3d** [sheyabernstein/MMM-shabbat#4]
I would love to try this however no matter what I do it tells me it can't find the sources and doesn't show up on the screen.  I'm rather a beginner, can someone help?

TIA!

**Comment by sheyabernstein** [comment]
Hi, can you share your config for the module and any error messages or screenshots?

Your config should look something like this;

```javascript
{
    module: 'MMM-shabbat',
    position: 'top_left',
    title: 'Zmanim',
    config: {
        latitude: 31.76904,
        longitude: 35.21633,
        tzid: 'Europe/London',
    }
}
```

**Comment by varek3d** [comment]
After re-installing everything it started working, I appreciate the quick responce.  Thank you and sorry to bother you.
